TRAINER:
    pretrain: False     # If you want to continue training a pretrained model, set path to pretrain model
    resume: False       # If you want to resume training a pretrained model, set path to pretrain model
    print_freq: 10
    meta_val_way: 5
    meta_val_shot: 1
    meta_val_metric: 'cosine'  # ('euclidean', 'cosine', 'l1', l2')
    meta_val_iter: 500
    meta_val_query: 15
    alpha: -1.0
    label_smoothing: 0.

MODEL:
    arch: 'resnet18'

OPTIM:
    epochs: 90
    gamma: 0.1
    lr: 0.1
    lr_stepsize: 30
    nesterov: False
    weight_decay: 0.0001
    optimizer_name: 'SGD'
    scheduler: 'multi_step'

DATA:
    dataset: 'inatural'
    root: 'data'
    dataset_path: 'inatural/setup'
    num_classes_train: 908
    num_classes_test: 227
    batch_size_loader: 256
    enlarge: True
    num_workers: 0
    disable_random_resize: False
    jitter: False
    path: 'data'
    split_dir: 'split/inatural'
    target_data_path:
    target_split_dir:

DISTRIBUTED:
    cuda: True
    visdom_port:
    seed: 2020
    ckpt_path: 'checkpoints/inatural/softmax/resnet18' # path model checkpoint
    log_path: 'logs' # path to where log files will be saved 
